### ISSUE TITLE
Beschrijving kaartlaag 2-labelstap aanpassen

### ISSUE THREAD

**Issue by VincentKamphuis** [PICOGH/Webviewer#1]
Enkel labels E, F en G maken een 2-labelstap voor deze kaartlagen.

**Comment by MaartenKrieckaert** [comment]
Gedaan, tekst is nu voor bv. gaspbesparing:  "De gemiddelde gasbesparing per woning na het verbeteren van de isolatie met twee labelstappen ten opzichte van het huidige label (alleen voor woningen met label E, F of G). Berekend door het Vesta model van PBL, toegepast door TNO."
