### ISSUE TITLE
Aanpassen WKO CO2 besparing kaartlaag

### ISSUE THREAD

**Issue by VincentKamphuis** [PICOGH/Webviewer#5]
Uit de mailwisseling:

Het is inderdaad zo dat WKO per GJ meer CO2 uitstoot dan gas. Echter: het gasverbruik bij WKO is lager vanwege de isolatie naar een label A+. De formule is dus: 56.24 kg/GJ \* warmteverbruik referentie woning 2020 – 64.49 kg/GJ \* warmteverbruik A+ woning 2020, en dit is dus wel > 0. Overigens laadt de CO2 WKO kaart voor mij niet in de Webviewer? Is dit inmiddels aangepast? De kaartlaag in de webviewer geeft nu voor elk gebied NVT?

**Comment by MaartenKrieckaert** [comment]
Gedaan. Het klopt dat je niks zag; de laag deed het wel, maar de legenda loopt vanaf >0 en alle waarden waren negatief ;)
