### ISSUE TITLE
Fix kaartlaag gebouwen

### ISSUE THREAD

**Issue by VincentKamphuis** [PICOGH/Webviewer#9]
Deze kaartlaag laadt niet.

![image](https://cloud.githubusercontent.com/assets/12395999/9758500/500a5616-56e7-11e5-84c2-fa451e582406.png)

**Comment by MaartenKrieckaert** [comment]
Deze laag doet het nu, maar je moet wel ver inzoomen (niveau #11)

**Comment by VincentKamphuis** [comment]
Top!
